import os
BASE_DIR = os.environ.get("BASE_DIR", "/work/FAC/FGSE/IDYST/tbeucler/downscaling")
DATASETS_TRAINING_DIR= os.environ.get("DATASETS_TRAINING_DIR", f"{BASE_DIR}/sasthana/Downscaling/Downscaling_Models/Dataset_Setup_I_Chronological_12km")
TARGET_DIR= os.environ.get("TARGET_DIR", f"{BASE_DIR}/sasthana/Downscaling/Processing_and_Analysis_Scripts/data_1971_2023/HR_files_full")   
BC_SCRIPTS= os.environ.get("BC_SCRIPTS", f"{BASE_DIR}/sasthana/Downscaling/GCM_pipeline/BC_methods")
BIAS_CORRECTED_DIR_SSP370= os.environ.get("BIAS_CORRECTED_DIR_RCP85", f"{BASE_DIR}/sasthana/Downscaling/GCM_pipeline/ALP-FINEv1.0/BC")
SCRATCH_DIR= os.environ.get("SCRATCH_DIR", f"/scratch/sasthana")
DDIM_PROJ_PATH= os.environ.get("DDIM_PROJ_PATH", f"{BASE_DIR}/sasthana/Downscaling/Downscaling_Models/DDIM_conditional_derived")
LDM_PROJ_PATH= os.environ.get("LDM_PROJ_PATH", f"{BASE_DIR}/sasthana/Downscaling/Downscaling_Models/LDM_conditional")
DM_DIR= os.environ.get("Downscaling_Models", f"{BASE_DIR}/sasthana/Downscaling/Downscaling_Models")